In [8]:
import pandas as pd
df=pd.read_csv("C:\\Users\\rheya_8e1lx53\\Projects\\health-outcomes.csv")
df

,Country,Infants exclusively breastfed (% ages 0Ð5 months) 2008Ð2013,Infants lacking immunization (% of one-year-olds) DTP 2013,Infants lacking immunization (% of one-year-olds) Measles 2013,"Mortality rates (per 1,000 live births) Infant 2013","Mortality rates (per 1,000 live births) Under-five 2013",Child malnutrition (% under age 5) Stunting (moderate or severe) 2008Ð2013,"Adult mortality rate (per 1,000 people) Female 2013","Adult mortality rate (per 1,000 people) Male 2013","Deaths due to Malaria (per 100,000 people) 2012","Deaths due to Tuberculosis (per 100,000 people) 2012","HIV prevalence, adult (% ages 15Ð49) 2013",Life expectancy at age 60 (years) 2010/2015,"Physicians (per 10,000 people) 2001Ð2013",Public health expenditure (% of GDP) 2013
0,Norway,NaN,1.0,7.0,2.3,2.8,NaN,47.0,73.0,NaN,0.1,NaN,24.0,37.4,9.6
1,Netherlands,NaN,1.0,4.0,3.3,4.0,NaN,54.0,69.0,NaN,0.2,NaN,23.5,31.5,12.9
2,Sweden,NaN,1.0,3.0,2.4,3.0,NaN,43.0,69.0,NaN,0.1,NaN,24.1,32.7,9.7
3,Korea (Republic of),NaN,1.0,1.0,3.2,3.7,2.5,38.0,93.0,0.0,5.4,NaN,24.0,21.4,7.2
4,Luxembourg,NaN,1.0,5.0,1.6,2.0,NaN,50.0,79.0,NaN,0.4,NaN,23.4,28.2,7.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
205,Chad,3.4,45.0,41.0,88.5,147.5,38.7,377.0,410.0,152.6,18.0,2.5,15.6,0.4,3.6
206,Somalia,9.1,48.0,54.0,89.8,145.6,42.1,289.0,339.0,33.5,64.0,0.5,16.1,0.4,NaN
207,Central African Republic,34.3,65.0,75.0,96.1,139.2,40.7,412.0,433.0,114.9,50.0,3.8,15.9,0.5,3.9
208,"Hong Kong, China (SAR)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.6,NaN,25.4,NaN,NaN
209,Liechtenstein,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
newdf=df.fillna(0)
newdf

,Country,Infants exclusively breastfed (% ages 0Ð5 months) 2008Ð2013,Infants lacking immunization (% of one-year-olds) DTP 2013,Infants lacking immunization (% of one-year-olds) Measles 2013,"Mortality rates (per 1,000 live births) Infant 2013","Mortality rates (per 1,000 live births) Under-five 2013",Child malnutrition (% under age 5) Stunting (moderate or severe) 2008Ð2013,"Adult mortality rate (per 1,000 people) Female 2013","Adult mortality rate (per 1,000 people) Male 2013","Deaths due to Malaria (per 100,000 people) 2012","Deaths due to Tuberculosis (per 100,000 people) 2012","HIV prevalence, adult (% ages 15Ð49) 2013",Life expectancy at age 60 (years) 2010/2015,"Physicians (per 10,000 people) 2001Ð2013",Public health expenditure (% of GDP) 2013
0,Norway,0.0,1.0,7.0,2.3,2.8,0.0,47.0,73.0,0.0,0.1,0.0,24.0,37.4,9.6
1,Netherlands,0.0,1.0,4.0,3.3,4.0,0.0,54.0,69.0,0.0,0.2,0.0,23.5,31.5,12.9
2,Sweden,0.0,1.0,3.0,2.4,3.0,0.0,43.0,69.0,0.0,0.1,0.0,24.1,32.7,9.7
3,Korea (Republic of),0.0,1.0,1.0,3.2,3.7,2.5,38.0,93.0,0.0,5.4,0.0,24.0,21.4,7.2
4,Luxembourg,0.0,1.0,5.0,1.6,2.0,0.0,50.0,79.0,0.0,0.4,0.0,23.4,28.2,7.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
205,Chad,3.4,45.0,41.0,88.5,147.5,38.7,377.0,410.0,152.6,18.0,2.5,15.6,0.4,3.6
206,Somalia,9.1,48.0,54.0,89.8,145.6,42.1,289.0,339.0,33.5,64.0,0.5,16.1,0.4,0.0
207,Central African Republic,34.3,65.0,75.0,96.1,139.2,40.7,412.0,433.0,114.9,50.0,3.8,15.9,0.5,3.9
208,"Hong Kong, China (SAR)",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.6,0.0,25.4,0.0,0.0
209,Liechtenstein,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [12]:
newdf=df.fillna({
    'Deaths due to Malaria (per 100,000 people) 2012' : 0,
    'Child malnutrition (% under age 5) Stunting (moderate or severe) 2008Ð2013':'no event'  
})
newdf

,Country,Infants exclusively breastfed (% ages 0Ð5 months) 2008Ð2013,Infants lacking immunization (% of one-year-olds) DTP 2013,Infants lacking immunization (% of one-year-olds) Measles 2013,"Mortality rates (per 1,000 live births) Infant 2013","Mortality rates (per 1,000 live births) Under-five 2013",Child malnutrition (% under age 5) Stunting (moderate or severe) 2008Ð2013,"Adult mortality rate (per 1,000 people) Female 2013","Adult mortality rate (per 1,000 people) Male 2013","Deaths due to Malaria (per 100,000 people) 2012","Deaths due to Tuberculosis (per 100,000 people) 2012","HIV prevalence, adult (% ages 15Ð49) 2013",Life expectancy at age 60 (years) 2010/2015,"Physicians (per 10,000 people) 2001Ð2013",Public health expenditure (% of GDP) 2013
0,Norway,NaN,1.0,7.0,2.3,2.8,no event,47.0,73.0,0.0,0.1,NaN,24.0,37.4,9.6
1,Netherlands,NaN,1.0,4.0,3.3,4.0,no event,54.0,69.0,0.0,0.2,NaN,23.5,31.5,12.9
2,Sweden,NaN,1.0,3.0,2.4,3.0,no event,43.0,69.0,0.0,0.1,NaN,24.1,32.7,9.7
3,Korea (Republic of),NaN,1.0,1.0,3.2,3.7,2.5,38.0,93.0,0.0,5.4,NaN,24.0,21.4,7.2
4,Luxembourg,NaN,1.0,5.0,1.6,2.0,no event,50.0,79.0,0.0,0.4,NaN,23.4,28.2,7.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
205,Chad,3.4,45.0,41.0,88.5,147.5,38.7,377.0,410.0,152.6,18.0,2.5,15.6,0.4,3.6
206,Somalia,9.1,48.0,54.0,89.8,145.6,42.1,289.0,339.0,33.5,64.0,0.5,16.1,0.4,NaN
207,Central African Republic,34.3,65.0,75.0,96.1,139.2,40.7,412.0,433.0,114.9,50.0,3.8,15.9,0.5,3.9
208,"Hong Kong, China (SAR)",NaN,NaN,NaN,NaN,NaN,no event,NaN,NaN,0.0,2.6,NaN,25.4,NaN,NaN
209,Liechtenstein,NaN,NaN,NaN,NaN,NaN,no event,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN

In [16]:
newdf=df.fillna(method="ffill")
newdf

C:\Users\rheya_8e1lx53\AppData\Local\Temp\ipykernel_122932\3060404463.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  newdf=df.fillna(method="ffill")

,Country,Infants exclusively breastfed (% ages 0Ð5 months) 2008Ð2013,Infants lacking immunization (% of one-year-olds) DTP 2013,Infants lacking immunization (% of one-year-olds) Measles 2013,"Mortality rates (per 1,000 live births) Infant 2013","Mortality rates (per 1,000 live births) Under-five 2013",Child malnutrition (% under age 5) Stunting (moderate or severe) 2008Ð2013,"Adult mortality rate (per 1,000 people) Female 2013","Adult mortality rate (per 1,000 people) Male 2013","Deaths due to Malaria (per 100,000 people) 2012","Deaths due to Tuberculosis (per 100,000 people) 2012","HIV prevalence, adult (% ages 15Ð49) 2013",Life expectancy at age 60 (years) 2010/2015,"Physicians (per 10,000 people) 2001Ð2013",Public health expenditure (% of GDP) 2013
0,Norway,NaN,1.0,7.0,2.3,2.8,NaN,47.0,73.0,NaN,0.1,NaN,24.0,37.4,9.6
1,Netherlands,NaN,1.0,4.0,3.3,4.0,NaN,54.0,69.0,NaN,0.2,NaN,23.5,31.5,12.9
2,Sweden,NaN,1.0,3.0,2.4,3.0,NaN,43.0,69.0,NaN,0.1,NaN,24.1,32.7,9.7
3,Korea (Republic of),NaN,1.0,1.0,3.2,3.7,2.5,38.0,93.0,0.0,5.4,NaN,24.0,21.4,7.2
4,Luxembourg,NaN,1.0,5.0,1.6,2.0,2.5,50.0,79.0,0.0,0.4,NaN,23.4,28.2,7.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
205,Chad,3.4,45.0,41.0,88.5,147.5,38.7,377.0,410.0,152.6,18.0,2.5,15.6,0.4,3.6
206,Somalia,9.1,48.0,54.0,89.8,145.6,42.1,289.0,339.0,33.5,64.0,0.5,16.1,0.4,3.6
207,Central African Republic,34.3,65.0,75.0,96.1,139.2,40.7,412.0,433.0,114.9,50.0,3.8,15.9,0.5,3.9
208,"Hong Kong, China (SAR)",34.3,65.0,75.0,96.1,139.2,40.7,412.0,433.0,114.9,2.6,3.8,25.4,0.5,3.9
209,Liechtenstein,34.3,65.0,75.0,96.1,139.2,40.7,412.0,433.0,114.9,2.6,3.8,25.4,0.5,3.9

In [2]:
import pandas as pd
df=pd.read_csv("C:\\Users\\rheya_8e1lx53\\Projects\\health-outcomes.csv")
newdf=df.fillna(method="bfill",axis="columns")
newdf

C:\Users\rheya_8e1lx53\AppData\Local\Temp\ipykernel_16552\2416131358.py:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  newdf=df.fillna(method="bfill",axis="columns")

,Country,Infants exclusively breastfed (% ages 0Ð5 months) 2008Ð2013,Infants lacking immunization (% of one-year-olds) DTP 2013,Infants lacking immunization (% of one-year-olds) Measles 2013,"Mortality rates (per 1,000 live births) Infant 2013","Mortality rates (per 1,000 live births) Under-five 2013",Child malnutrition (% under age 5) Stunting (moderate or severe) 2008Ð2013,"Adult mortality rate (per 1,000 people) Female 2013","Adult mortality rate (per 1,000 people) Male 2013","Deaths due to Malaria (per 100,000 people) 2012","Deaths due to Tuberculosis (per 100,000 people) 2012","HIV prevalence, adult (% ages 15Ð49) 2013",Life expectancy at age 60 (years) 2010/2015,"Physicians (per 10,000 people) 2001Ð2013",Public health expenditure (% of GDP) 2013
0,Norway,1.0,1.0,7.0,2.3,2.8,47.0,47.0,73.0,0.1,0.1,24.0,24.0,37.4,9.6
1,Netherlands,1.0,1.0,4.0,3.3,4.0,54.0,54.0,69.0,0.2,0.2,23.5,23.5,31.5,12.9
2,Sweden,1.0,1.0,3.0,2.4,3.0,43.0,43.0,69.0,0.1,0.1,24.1,24.1,32.7,9.7
3,Korea (Republic of),1.0,1.0,1.0,3.2,3.7,2.5,38.0,93.0,0.0,5.4,24.0,24.0,21.4,7.2
4,Luxembourg,1.0,1.0,5.0,1.6,2.0,50.0,50.0,79.0,0.4,0.4,23.4,23.4,28.2,7.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
205,Chad,3.4,45.0,41.0,88.5,147.5,38.7,377.0,410.0,152.6,18.0,2.5,15.6,0.4,3.6
206,Somalia,9.1,48.0,54.0,89.8,145.6,42.1,289.0,339.0,33.5,64.0,0.5,16.1,0.4,NaN
207,Central African Republic,34.3,65.0,75.0,96.1,139.2,40.7,412.0,433.0,114.9,50.0,3.8,15.9,0.5,3.9
208,"Hong Kong, China (SAR)",2.6,2.6,2.6,2.6,2.6,2.6,2.6,2.6,2.6,2.6,25.4,25.4,NaN,NaN
209,Liechtenstein,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df=pd.read_csv("C:\\Users\\rheya_8e1lx53\\Projects\\health-outcomes.csv")
newdf=df.fillna(method="bfill",limit=1)
newdf

C:\Users\rheya_8e1lx53\AppData\Local\Temp\ipykernel_16552\3102026801.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  newdf=df.fillna(method="bfill",limit=1)

,Country,Infants exclusively breastfed (% ages 0Ð5 months) 2008Ð2013,Infants lacking immunization (% of one-year-olds) DTP 2013,Infants lacking immunization (% of one-year-olds) Measles 2013,"Mortality rates (per 1,000 live births) Infant 2013","Mortality rates (per 1,000 live births) Under-five 2013",Child malnutrition (% under age 5) Stunting (moderate or severe) 2008Ð2013,"Adult mortality rate (per 1,000 people) Female 2013","Adult mortality rate (per 1,000 people) Male 2013","Deaths due to Malaria (per 100,000 people) 2012","Deaths due to Tuberculosis (per 100,000 people) 2012","HIV prevalence, adult (% ages 15Ð49) 2013",Life expectancy at age 60 (years) 2010/2015,"Physicians (per 10,000 people) 2001Ð2013",Public health expenditure (% of GDP) 2013
0,Norway,NaN,1.0,7.0,2.3,2.8,NaN,47.0,73.0,NaN,0.1,NaN,24.0,37.4,9.6
1,Netherlands,NaN,1.0,4.0,3.3,4.0,NaN,54.0,69.0,NaN,0.2,NaN,23.5,31.5,12.9
2,Sweden,NaN,1.0,3.0,2.4,3.0,2.5,43.0,69.0,0.0,0.1,NaN,24.1,32.7,9.7
3,Korea (Republic of),NaN,1.0,1.0,3.2,3.7,2.5,38.0,93.0,0.0,5.4,NaN,24.0,21.4,7.2
4,Luxembourg,NaN,1.0,5.0,1.6,2.0,NaN,50.0,79.0,NaN,0.4,NaN,23.4,28.2,7.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
205,Chad,3.4,45.0,41.0,88.5,147.5,38.7,377.0,410.0,152.6,18.0,2.5,15.6,0.4,3.6
206,Somalia,9.1,48.0,54.0,89.8,145.6,42.1,289.0,339.0,33.5,64.0,0.5,16.1,0.4,3.9
207,Central African Republic,34.3,65.0,75.0,96.1,139.2,40.7,412.0,433.0,114.9,50.0,3.8,15.9,0.5,3.9
208,"Hong Kong, China (SAR)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.6,NaN,25.4,NaN,NaN
209,Liechtenstein,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
newdf=df.interpolate()
newdf

C:\Users\rheya_8e1lx53\AppData\Local\Temp\ipykernel_16552\2712138379.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  newdf=df.interpolate()

,Country,Infants exclusively breastfed (% ages 0Ð5 months) 2008Ð2013,Infants lacking immunization (% of one-year-olds) DTP 2013,Infants lacking immunization (% of one-year-olds) Measles 2013,"Mortality rates (per 1,000 live births) Infant 2013","Mortality rates (per 1,000 live births) Under-five 2013",Child malnutrition (% under age 5) Stunting (moderate or severe) 2008Ð2013,"Adult mortality rate (per 1,000 people) Female 2013","Adult mortality rate (per 1,000 people) Male 2013","Deaths due to Malaria (per 100,000 people) 2012","Deaths due to Tuberculosis (per 100,000 people) 2012","HIV prevalence, adult (% ages 15Ð49) 2013",Life expectancy at age 60 (years) 2010/2015,"Physicians (per 10,000 people) 2001Ð2013",Public health expenditure (% of GDP) 2013
0,Norway,NaN,1.0,7.0,2.3,2.8,NaN,47.0,73.0,NaN,0.1,NaN,24.0,37.4,9.60
1,Netherlands,NaN,1.0,4.0,3.3,4.0,NaN,54.0,69.0,NaN,0.2,NaN,23.5,31.5,12.90
2,Sweden,NaN,1.0,3.0,2.4,3.0,NaN,43.0,69.0,NaN,0.1,NaN,24.1,32.7,9.70
3,Korea (Republic of),NaN,1.0,1.0,3.2,3.7,2.500000,38.0,93.0,0.000000,5.4,NaN,24.0,21.4,7.20
4,Luxembourg,NaN,1.0,5.0,1.6,2.0,2.514286,50.0,79.0,0.041667,0.4,NaN,23.4,28.2,7.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
205,Chad,3.4,45.0,41.0,88.5,147.5,38.700000,377.0,410.0,152.600000,18.0,2.5,15.6,0.4,3.60
206,Somalia,9.1,48.0,54.0,89.8,145.6,42.100000,289.0,339.0,33.500000,64.0,0.5,16.1,0.4,3.75
207,Central African Republic,34.3,65.0,75.0,96.1,139.2,40.700000,412.0,433.0,114.900000,50.0,3.8,15.9,0.5,3.90
208,"Hong Kong, China (SAR)",34.3,65.0,75.0,96.1,139.2,40.700000,412.0,433.0,114.900000,2.6,3.8,25.4,0.5,3.90
209,Liechtenstein,34.3,65.0,75.0,96.1,139.2,40.700000,412.0,433.0,114.900000,2.6,3.8,25.4,0.5,3.90

In [9]:
newdf=df.dropna(thresh=2)
newdf

,Country,Infants exclusively breastfed (% ages 0Ð5 months) 2008Ð2013,Infants lacking immunization (% of one-year-olds) DTP 2013,Infants lacking immunization (% of one-year-olds) Measles 2013,"Mortality rates (per 1,000 live births) Infant 2013","Mortality rates (per 1,000 live births) Under-five 2013",Child malnutrition (% under age 5) Stunting (moderate or severe) 2008Ð2013,"Adult mortality rate (per 1,000 people) Female 2013","Adult mortality rate (per 1,000 people) Male 2013","Deaths due to Malaria (per 100,000 people) 2012","Deaths due to Tuberculosis (per 100,000 people) 2012","HIV prevalence, adult (% ages 15Ð49) 2013",Life expectancy at age 60 (years) 2010/2015,"Physicians (per 10,000 people) 2001Ð2013",Public health expenditure (% of GDP) 2013
0,Norway,NaN,1.0,7.0,2.3,2.8,NaN,47.0,73.0,NaN,0.1,NaN,24.0,37.4,9.6
1,Netherlands,NaN,1.0,4.0,3.3,4.0,NaN,54.0,69.0,NaN,0.2,NaN,23.5,31.5,12.9
2,Sweden,NaN,1.0,3.0,2.4,3.0,NaN,43.0,69.0,NaN,0.1,NaN,24.1,32.7,9.7
3,Korea (Republic of),NaN,1.0,1.0,3.2,3.7,2.5,38.0,93.0,0.0,5.4,NaN,24.0,21.4,7.2
4,Luxembourg,NaN,1.0,5.0,1.6,2.0,NaN,50.0,79.0,NaN,0.4,NaN,23.4,28.2,7.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
204,Equatorial Guinea,7.4,45.0,58.0,69.3,95.8,26.2,319.0,368.0,69.3,0.0,NaN,15.9,3.0,3.5
205,Chad,3.4,45.0,41.0,88.5,147.5,38.7,377.0,410.0,152.6,18.0,2.5,15.6,0.4,3.6
206,Somalia,9.1,48.0,54.0,89.8,145.6,42.1,289.0,339.0,33.5,64.0,0.5,16.1,0.4,NaN
207,Central African Republic,34.3,65.0,75.0,96.1,139.2,40.7,412.0,433.0,114.9,50.0,3.8,15.9,0.5,3.9
208,"Hong Kong, China (SAR)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.6,NaN,25.4,NaN,NaN