In [1]:
import pandas as pd
df=pd.read_csv("C:\\Users\\rheya_8e1lx53\\Projects\\Weather_Data.csv")
df

,Date,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,2/1/2008,19.5,22.4,15.6,6.2,0.0,W,41,S,SSW,...,92,84,1017.6,1017.4,8,8,20.7,20.9,Yes,Yes
1,2/2/2008,19.5,25.6,6.0,3.4,2.7,W,41,W,E,...,83,73,1017.9,1016.4,7,7,22.4,24.8,Yes,Yes
2,2/3/2008,21.6,24.5,6.6,2.4,0.1,W,41,ESE,ESE,...,88,86,1016.7,1015.6,7,8,23.5,23.0,Yes,Yes
3,2/4/2008,20.2,22.8,18.8,2.2,0.0,W,41,NNE,E,...,83,90,1014.2,1011.8,8,8,21.4,20.9,Yes,Yes
4,2/5/2008,19.7,25.7,77.4,4.8,0.0,W,41,NNE,W,...,88,74,1008.3,1004.8,8,8,22.5,25.5,Yes,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3266,6/21/2017,8.6,19.6,0.0,2.0,7.8,SSE,37,W,SSE,...,73,52,1025.9,1025.3,2,2,10.5,17.9,No,No
3267,6/22/2017,9.3,19.2,0.0,2.0,9.2,W,30,W,ESE,...,78,53,1028.5,1024.6,2,2,11.0,18.7,No,No
3268,6/23/2017,9.4,17.7,0.0,2.4,2.7,W,24,WNW,N,...,85,56,1020.8,1015.0,6,6,10.2,17.3,No,No
3269,6/24/2017,10.1,19.3,0.0,1.4,9.3,W,43,W,W,...,56,35,1017.3,1015.1,5,2,12.4,19.0,No,No
3270,6/25/2017,7.6,19.3,0.0,3.4,9.4,W,35,W,W,...,73,32,1018.6,1015.4,1,1,9.4,18.8,No,No

In [5]:
rows,columns=df.shape
columns

22

In [6]:
df.head()

,Date,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,2/1/2008,19.5,22.4,15.6,6.2,0.0,W,41,S,SSW,...,92,84,1017.6,1017.4,8,8,20.7,20.9,Yes,Yes
1,2/2/2008,19.5,25.6,6.0,3.4,2.7,W,41,W,E,...,83,73,1017.9,1016.4,7,7,22.4,24.8,Yes,Yes
2,2/3/2008,21.6,24.5,6.6,2.4,0.1,W,41,ESE,ESE,...,88,86,1016.7,1015.6,7,8,23.5,23.0,Yes,Yes
3,2/4/2008,20.2,22.8,18.8,2.2,0.0,W,41,NNE,E,...,83,90,1014.2,1011.8,8,8,21.4,20.9,Yes,Yes
4,2/5/2008,19.7,25.7,77.4,4.8,0.0,W,41,NNE,W,...,88,74,1008.3,1004.8,8,8,22.5,25.5,Yes,Yes

In [8]:
df.tail(1)

,Date,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
3270,6/25/2017,7.6,19.3,0.0,3.4,9.4,W,35,W,W,...,73,32,1018.6,1015.4,1,1,9.4,18.8,No,No

In [9]:
df[2:5]

,Date,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
2,2/3/2008,21.6,24.5,6.6,2.4,0.1,W,41,ESE,ESE,...,88,86,1016.7,1015.6,7,8,23.5,23.0,Yes,Yes
3,2/4/2008,20.2,22.8,18.8,2.2,0.0,W,41,NNE,E,...,83,90,1014.2,1011.8,8,8,21.4,20.9,Yes,Yes
4,2/5/2008,19.7,25.7,77.4,4.8,0.0,W,41,NNE,W,...,88,74,1008.3,1004.8,8,8,22.5,25.5,Yes,Yes

In [10]:
df[:]

,Date,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,2/1/2008,19.5,22.4,15.6,6.2,0.0,W,41,S,SSW,...,92,84,1017.6,1017.4,8,8,20.7,20.9,Yes,Yes
1,2/2/2008,19.5,25.6,6.0,3.4,2.7,W,41,W,E,...,83,73,1017.9,1016.4,7,7,22.4,24.8,Yes,Yes
2,2/3/2008,21.6,24.5,6.6,2.4,0.1,W,41,ESE,ESE,...,88,86,1016.7,1015.6,7,8,23.5,23.0,Yes,Yes
3,2/4/2008,20.2,22.8,18.8,2.2,0.0,W,41,NNE,E,...,83,90,1014.2,1011.8,8,8,21.4,20.9,Yes,Yes
4,2/5/2008,19.7,25.7,77.4,4.8,0.0,W,41,NNE,W,...,88,74,1008.3,1004.8,8,8,22.5,25.5,Yes,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3266,6/21/2017,8.6,19.6,0.0,2.0,7.8,SSE,37,W,SSE,...,73,52,1025.9,1025.3,2,2,10.5,17.9,No,No
3267,6/22/2017,9.3,19.2,0.0,2.0,9.2,W,30,W,ESE,...,78,53,1028.5,1024.6,2,2,11.0,18.7,No,No
3268,6/23/2017,9.4,17.7,0.0,2.4,2.7,W,24,WNW,N,...,85,56,1020.8,1015.0,6,6,10.2,17.3,No,No
3269,6/24/2017,10.1,19.3,0.0,1.4,9.3,W,43,W,W,...,56,35,1017.3,1015.1,5,2,12.4,19.0,No,No
3270,6/25/2017,7.6,19.3,0.0,3.4,9.4,W,35,W,W,...,73,32,1018.6,1015.4,1,1,9.4,18.8,No,No

In [11]:
df.columns

Index(['Date', 'MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation', 'Sunshine',
       'WindGustDir', 'WindGustSpeed', 'WindDir9am', 'WindDir3pm',
       'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm',
       'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm', 'Temp9am',
       'Temp3pm', 'RainToday', 'RainTomorrow'],
      dtype='object')

In [ ]:
df.Date#df['Date']

0        2/1/2008
1        2/2/2008
2        2/3/2008
3        2/4/2008
4        2/5/2008
          ...
3266    6/21/2017
3267    6/22/2017
3268    6/23/2017
3269    6/24/2017
3270    6/25/2017
Name: Date, Length: 3271, dtype: object

In [14]:
df[['Date','MinTemp','Rainfall']]

           Date  MinTemp  Rainfall
0      2/1/2008     19.5      15.6
1      2/2/2008     19.5       6.0
2      2/3/2008     21.6       6.6
3      2/4/2008     20.2      18.8
4      2/5/2008     19.7      77.4
...         ...      ...       ...
3266  6/21/2017      8.6       0.0
3267  6/22/2017      9.3       0.0
3268  6/23/2017      9.4       0.0
3269  6/24/2017     10.1       0.0
3270  6/25/2017      7.6       0.0

[3271 rows x 3 columns]

In [19]:
df['MinTemp'].std()

4.554710399931853

In [20]:
df.describe()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm
count,3271.000000,3271.000000,3271.000000,3271.000000,3271.000000,3271.000000,3271.000000,3271.000000,3271.000000,3271.000000,3271.000000,3271.000000,3271.000000,3271.000000,3271.000000,3271.000000
mean,14.877102,23.005564,3.342158,5.175787,7.168970,41.476307,15.077041,19.294405,68.243962,54.698563,1018.334424,1016.003085,4.318557,4.176093,17.821461,21.543656
std,4.554710,4.483752,9.917746,2.757684,3.815966,10.806951,7.043825,7.453331,15.086127,16.279241,7.020090,7.019915,2.526923,2.411274,4.894316,4.297053
min,4.300000,11.700000,0.000000,0.000000,0.000000,17.000000,0.000000,0.000000,19.000000,10.000000,986.700000,989.800000,0.000000,0.000000,6.400000,10.200000
25%,11.000000,19.600000,0.000000,3.200000,4.250000,35.000000,11.000000,15.000000,58.000000,44.000000,1013.700000,1011.300000,2.000000,2.000000,13.800000,18.400000
50%,14.900000,22.800000,0.000000,4.800000,8.300000,41.000000,15.000000,19.000000,69.000000,56.000000,1018.600000,1016.300000,5.000000,4.000000,18.200000,21.300000
75%,18.800000,26.000000,1.400000,7.000000,10.200000,44.000000,20.000000,24.000000,80.000000,64.000000,1023.100000,1020.800000,7.000000,7.000000,21.700000,24.500000
max,27.600000,45.800000,119.400000,18.400000,13.600000,96.000000,54.000000,57.000000,100.000000,99.000000,1039.000000,1036.700000,9.000000,8.000000,36.500000,44.700000

In [22]:
df[df.MinTemp>18]

,Date,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,2/1/2008,19.5,22.4,15.6,6.2,0.0,W,41,S,SSW,...,92,84,1017.6,1017.4,8,8,20.7,20.9,Yes,Yes
1,2/2/2008,19.5,25.6,6.0,3.4,2.7,W,41,W,E,...,83,73,1017.9,1016.4,7,7,22.4,24.8,Yes,Yes
2,2/3/2008,21.6,24.5,6.6,2.4,0.1,W,41,ESE,ESE,...,88,86,1016.7,1015.6,7,8,23.5,23.0,Yes,Yes
3,2/4/2008,20.2,22.8,18.8,2.2,0.0,W,41,NNE,E,...,83,90,1014.2,1011.8,8,8,21.4,20.9,Yes,Yes
4,2/5/2008,19.7,25.7,77.4,4.8,0.0,W,41,NNE,W,...,88,74,1008.3,1004.8,8,8,22.5,25.5,Yes,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3181,3/27/2017,19.2,27.0,0.0,5.8,11.0,NNE,41,W,NE,...,76,62,1017.1,1012.3,1,1,21.8,26.0,No,No
3182,3/28/2017,21.2,23.8,0.0,7.4,0.0,SSW,54,SSW,S,...,76,69,1013.9,1012.4,7,8,21.8,23.6,No,No
3183,3/29/2017,21.4,28.8,0.0,2.4,8.4,E,30,E,E,...,84,71,1012.3,1007.4,8,1,22.5,27.0,No,Yes
3184,3/30/2017,22.5,26.0,2.4,7.4,0.0,SSW,69,NNE,SSW,...,70,88,1007.0,1007.7,8,8,25.2,19.2,Yes,Yes
3210,4/25/2017,18.2,26.7,0.0,4.4,3.0,NW,39,E,NW,...,69,65,1014.0,1008.8,7,7,20.6,21.9,No,Yes

In [23]:
df[df.MaxTemp==df.MaxTemp.max()]

,Date,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
1696,1/18/2013,21.7,45.8,0.0,9.0,8.4,S,78,E,E,...,62,14,1002.9,997.9,0,3,28.9,44.7,No,No

In [28]:
df[df.MaxTemp==df.MaxTemp.max()][['Date','MaxTemp']]

           Date  MaxTemp
1696  1/18/2013     45.8

In [30]:
df.set_index('Date')

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
Date,,,,,,,,,,,,,,,,,,,,,
2/1/2008,19.5,22.4,15.6,6.2,0.0,W,41,S,SSW,17,...,92,84,1017.6,1017.4,8,8,20.7,20.9,Yes,Yes
2/2/2008,19.5,25.6,6.0,3.4,2.7,W,41,W,E,9,...,83,73,1017.9,1016.4,7,7,22.4,24.8,Yes,Yes
2/3/2008,21.6,24.5,6.6,2.4,0.1,W,41,ESE,ESE,17,...,88,86,1016.7,1015.6,7,8,23.5,23.0,Yes,Yes
2/4/2008,20.2,22.8,18.8,2.2,0.0,W,41,NNE,E,22,...,83,90,1014.2,1011.8,8,8,21.4,20.9,Yes,Yes
2/5/2008,19.7,25.7,77.4,4.8,0.0,W,41,NNE,W,11,...,88,74,1008.3,1004.8,8,8,22.5,25.5,Yes,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6/21/2017,8.6,19.6,0.0,2.0,7.8,SSE,37,W,SSE,22,...,73,52,1025.9,1025.3,2,2,10.5,17.9,No,No
6/22/2017,9.3,19.2,0.0,2.0,9.2,W,30,W,ESE,20,...,78,53,1028.5,1024.6,2,2,11.0,18.7,No,No
6/23/2017,9.4,17.7,0.0,2.4,2.7,W,24,WNW,N,15,...,85,56,1020.8,1015.0,6,6,10.2,17.3,No,No
6/24/2017,10.1,19.3,0.0,1.4,9.3,W,43,W,W,17,...,56,35,1017.3,1015.1,5,2,12.4,19.0,No,No
6/25/2017,7.6,19.3,0.0,3.4,9.4,W,35,W,W,13,...,73,32,1018.6,1015.4,1,1,9.4,18.8,No,No

In [32]:
df.set_index('Date',inplace=True)
df

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
Date,,,,,,,,,,,,,,,,,,,,,
2/1/2008,19.5,22.4,15.6,6.2,0.0,W,41,S,SSW,17,...,92,84,1017.6,1017.4,8,8,20.7,20.9,Yes,Yes
2/2/2008,19.5,25.6,6.0,3.4,2.7,W,41,W,E,9,...,83,73,1017.9,1016.4,7,7,22.4,24.8,Yes,Yes
2/3/2008,21.6,24.5,6.6,2.4,0.1,W,41,ESE,ESE,17,...,88,86,1016.7,1015.6,7,8,23.5,23.0,Yes,Yes
2/4/2008,20.2,22.8,18.8,2.2,0.0,W,41,NNE,E,22,...,83,90,1014.2,1011.8,8,8,21.4,20.9,Yes,Yes
2/5/2008,19.7,25.7,77.4,4.8,0.0,W,41,NNE,W,11,...,88,74,1008.3,1004.8,8,8,22.5,25.5,Yes,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6/21/2017,8.6,19.6,0.0,2.0,7.8,SSE,37,W,SSE,22,...,73,52,1025.9,1025.3,2,2,10.5,17.9,No,No
6/22/2017,9.3,19.2,0.0,2.0,9.2,W,30,W,ESE,20,...,78,53,1028.5,1024.6,2,2,11.0,18.7,No,No
6/23/2017,9.4,17.7,0.0,2.4,2.7,W,24,WNW,N,15,...,85,56,1020.8,1015.0,6,6,10.2,17.3,No,No
6/24/2017,10.1,19.3,0.0,1.4,9.3,W,43,W,W,17,...,56,35,1017.3,1015.1,5,2,12.4,19.0,No,No
6/25/2017,7.6,19.3,0.0,3.4,9.4,W,35,W,W,13,...,73,32,1018.6,1015.4,1,1,9.4,18.8,No,No

In [34]:
df.loc['6/24/2017']

MinTemp            10.1
MaxTemp            19.3
Rainfall            0.0
Evaporation         1.4
Sunshine            9.3
WindGustDir           W
WindGustSpeed        43
WindDir9am            W
WindDir3pm            W
WindSpeed9am         17
WindSpeed3pm         19
Humidity9am          56
Humidity3pm          35
Pressure9am      1017.3
Pressure3pm      1015.1
Cloud9am              5
Cloud3pm              2
Temp9am            12.4
Temp3pm            19.0
RainToday            No
RainTomorrow         No
Name: 6/24/2017, dtype: object

In [ ]:
df.reset_index(inplace=True)#default inplace=False
df

,Date,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,2/1/2008,19.5,22.4,15.6,6.2,0.0,W,41,S,SSW,...,92,84,1017.6,1017.4,8,8,20.7,20.9,Yes,Yes
1,2/2/2008,19.5,25.6,6.0,3.4,2.7,W,41,W,E,...,83,73,1017.9,1016.4,7,7,22.4,24.8,Yes,Yes
2,2/3/2008,21.6,24.5,6.6,2.4,0.1,W,41,ESE,ESE,...,88,86,1016.7,1015.6,7,8,23.5,23.0,Yes,Yes
3,2/4/2008,20.2,22.8,18.8,2.2,0.0,W,41,NNE,E,...,83,90,1014.2,1011.8,8,8,21.4,20.9,Yes,Yes
4,2/5/2008,19.7,25.7,77.4,4.8,0.0,W,41,NNE,W,...,88,74,1008.3,1004.8,8,8,22.5,25.5,Yes,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3266,6/21/2017,8.6,19.6,0.0,2.0,7.8,SSE,37,W,SSE,...,73,52,1025.9,1025.3,2,2,10.5,17.9,No,No
3267,6/22/2017,9.3,19.2,0.0,2.0,9.2,W,30,W,ESE,...,78,53,1028.5,1024.6,2,2,11.0,18.7,No,No
3268,6/23/2017,9.4,17.7,0.0,2.4,2.7,W,24,WNW,N,...,85,56,1020.8,1015.0,6,6,10.2,17.3,No,No
3269,6/24/2017,10.1,19.3,0.0,1.4,9.3,W,43,W,W,...,56,35,1017.3,1015.1,5,2,12.4,19.0,No,No
3270,6/25/2017,7.6,19.3,0.0,3.4,9.4,W,35,W,W,...,73,32,1018.6,1015.4,1,1,9.4,18.8,No,No